language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libpcap-dev
      - cmake-data
      - cmake
      - qtbase5-dev
      - vera++
before_script:
  - chmod +x tools/checkstyle/checkoplkstyle.sh
  - ./tools/checkstyle/checkoplkstyle.sh
script:
  - cd drivers/linux/drv_kernelmod_edrv/build/
  - cmake ..
  - cd ../../../../stack/build/linux
  - cmake ../..
  - make install
  - cd ../../../apps/demo_mn_console/build/linux
  - cmake ../..
  - make install
  - cd ../../../demo_mn_qt/build/linux
  - cmake ../..
  - make install
  - cd ../../../demo_cn_console/build/linux
  - cmake ../..
  - make install